FROM amazoncorretto:21-alpine-jdk as build
WORKDIR ~/app

COPY Hello.java Hello.java

RUN javac Hello.java

FROM eclipse-temurin:21-jre-alpine as run

COPY --from=build ~/app/Hello.class Hello.class

ENTRYPOINT java Hello







